### ISSUE TITLE
No way to set AWS_ACCESS_KEY_ID?

### ISSUE THREAD

**Issue by dpeek** [zeit/fun#18]
I see there are a set of env vars we're not allowed to set, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY included. Problem is when calling AWS SDK from inside a function I'd like to not have to pass those from somewhere else (which matches what happens in production).

Is there some other way of passing these in? If not could there be? :)

**Comment by TooTallNate** [comment]
You can set them manually from within your lambda code before using the AWS SDK.

**Comment by TooTallNate** [comment]
We could also add a configuration option for this, patch welcome 👍

**Comment by dpeek** [comment]
Currently setting them through the SDK as suggested, but seems cleaner to remove this local conditional logic and just do what happens in production. Will take a stab at a patch.

**Comment by TooTallNate** [comment]
Fixed in b6796d82a5425506cd382206e56add591e8c25eb.
