### ISSUE TITLE
How do you include dependencies?

### ISSUE THREAD

**Issue by bvkimball** [zeit/fun#25]
I tried using **@zeit/ncc** to compile to one file too, but i always get this error:

```
Error: Unable to import module 'index'
```

This is what i am trying to do.

```
const Octokit = require("@octokit/rest");
const octokit = new Octokit();

exports.handler = (event, context, callback) => {
  octokit.repos
    .listForOrg({
      org: "octokit",
      type: "public"
    })
    .then(repos => {
      callback(repos.data);
    });
};
```

i have tried to `const Octokit = require("@octokit/rest");` inside the handler too.
 
Any thoughts?

running with this setup:
```
  const fn = await createFunction({
    Code: {
      // `ZipFile` works, or an already unzipped directory may be specified
      Directory: __dirname + "/dist"
    },
    Handler: "index.handler",
    Runtime: "nodejs"
  });
```

**Comment by bvkimball** [comment]
so i got it to work with the node_modules included in that directory,

I guess it would be nice to get it to work with a single file build using ncc...

**Comment by rauchg** [comment]
@bvkimball could you tell us more about your use-case ?

**Comment by bvkimball** [comment]
@rauchg no specific use-case.  but i like the easy of use of `ncc` so that i could write the above function in typescript.  it compiles to a single 417kb file, as opposed to having 3.1MB folder that i have to zip.

I am trying to find a way to have several simple integration api like above but i want to manage them in 1 project then bundle them with ncc and think right now it would be easier to manage a single js file then a zip. 

> Only ship relevant app code to serverless environments

i was hoping maybe my tsconfig file was just wrong.

**Comment by rauchg** [comment]
This project's scope is to be able to run functions in localhost. It's a dependency of `now-cli` for `now dev`. Did you mean to open this issue under https://github.com/zeit/ncc ?

**Comment by bvkimball** [comment]
I am trying to run the functions on localhost, i could open the issue under `ncc` if you want but the file seems to compile just fine, but when `fun` tries to load the file i get `Error: Unable to import module 'index'
`
The bug/user_error is the above code when compiled to a single file by `ncc` can NOT be run by @zeit/fun when used as so:

```
const fn = await createFunction({
    Code: {
      Directory: __dirname + "/dist"
    },
    Handler: "index.handler",
    Runtime: "nodejs"
  });
```

**Comment by rauchg** [comment]
Gotcha! Makes sense.

Not sure how to fix this (@TooTallNate might want to chime in), but what you are trying to do is done automatically by `now dev`:

- The process of bundling a Node.js function is facilitated by `@now/node`, which uses `@zeit/ncc` under the hood
- `now dev` uses `@zeit/fun` to invoke the bundled function

**Comment by bvkimball** [comment]
this was all my fault caused by https://github.com/octokit/rest.js/issues/1400 
I moved the `require` inside the `handler` function the module loaded but gave me an error that `request-error` couldn't load.  A million apologies, everything works as expected now.
